### PR TITLE
Add before/after hooks to run custom actions

### PR DESCRIPTION
**Pull request by hammady**
Sometimes it is needed to run custom commands either before, after or before and after playing adhan. For example, if you have
[Quran playing continuously](https://github.com/LintangWisesa/RPi_QuranSpeaker), you would want to pause and resume the playback. Another example, is to set your status on a social network, or a calendar, to block/unblock the Internet using [pi.hole rules](https://docs.pi-hole.net/), ... etc.

You can easily do this by adding scripts in the following directories:
- `before-hooks.d`: Scripts to run before adhan playback
- `after-hooks.d`: Scripts to run after adhan playback

### Example:
To pause/resume Quran playback if using the [RPi_QuranSpeaker](https://github.com/LintangWisesa/RPi_QuranSpeaker) project, place the following in a new file (e.g. `01-pause-quran-speaker.sh`) under the above 2 directories:

```bash
#!/usr/bin/env bash
/home/pi/RPi_QuranSpeaker/pauser.py
```

Do not forget to make the scripts executable:
```bash
chmod u+x ./{before,after}-hooks.d/01-pause-quran-speaker.sh
```

### CODE REVIEW

**Comment by hammady** [comment]
@achaudhry any chance to review this? I'm using it since then with no problems.

**Comment by achaudhry** [comment]
Yes I'm so sorry to sit on this for so long. Been extremely busy so never got around to it. I'll review/test this in the next couple of days tops.

**Review by achaudhry — APPROVED** [review]

**Comment by achaudhry** [comment]
This completely fell off my radar. Just merged it!

**Comment by hammady** [comment]
lol better late than never 😅 Eid Mubarak!

**Pull request merged**
